class WhatsNewVersion {
  final String version;
  final String title;
  final String description;
  final String verification;

  const WhatsNewVersion({
    required this.version,
    required this.title,
    required this.description,
    required this.verification,
  });

  static List<WhatsNewVersion> getVersions(bool isFr) {
    return [
      WhatsNewVersion(
        version: '1.5.105',
        title: isFr
            ? 'Connexion OIDC & Corrections Importantes'
            : 'OIDC Connection & Important Fixes',
        description: isFr
            ? 'Nouveau : Choix entre connexion Classique et OIDC lors de l\u2019ajout d\u2019un appareil. Correction automatique des utilisateurs OIDC créés sans nom (email utilisé comme nom). Correction d\u2019un bug d\u2019affichage du graphe ACL. Suppression des warnings de dépréciation.'
            : 'New: Choose between Classic and OIDC connection when adding a device. Auto-fix for OIDC users created without a name (email used as name). Fixed ACL graph display bug. Removed deprecation warnings.',
        verification: isFr
            ? 'Écran Utilisateur > Nouvel Appareil > choisir le mode de connexion.'
            : 'User Screen > New Device > choose connection mode.',
      ),
      WhatsNewVersion(
        version: '1.5.104',
        title: isFr
            ? 'Gestion des Clés API Restaurée'
            : 'API Key Management Restored',
        description: isFr
            ? 'L\'écran de gestion des clés API est de retour ! Accessible depuis les Paramètres avec un design modernisé. Gérez vos clés d\'administration en toute sécurité.'
            : 'The API Key management screen is back! Accessible from Settings with a modernized design. Manage your admin keys securely.',
        verification: isFr
            ? 'Paramètres > Bouton (+) > Clés API'
            : 'Settings > (+) Button > API Keys',
      ),
      WhatsNewVersion(
        version: '1.5.103',
        title: isFr
            ? 'Support des Commentaires ACL (HuJSON)'
            : 'ACL Comments Support (HuJSON)',
        description: isFr
            ? 'Les commentaires (//) dans vos ACL sont désormais correctement gérés par les vues Graphique et Puzzle. Plus de crash lors de la visualisation de configurations complexes !'
            : 'Comments (//) in your ACLs are now correctly handled by Graph and Puzzle views. No more crashes when viewing complex configurations!',
        verification: isFr
            ? 'Ajoutez un commentaire "// test" dans l\'éditeur ACL et ouvrez la vue Puzzle.'
            : 'Add a "// test" comment in the ACL editor and open the Puzzle view.',
      ),
      WhatsNewVersion(
        version: '1.5.102',
        title:
            isFr ? 'Support OIDC Avancé & ACLs' : 'Advanced OIDC & ACL Support',
        description: isFr
            ? 'Mise à jour majeure pour OIDC ! Support des noms d\'utilisateurs type email (user@domaine.com) pour s\'aligner avec les ACLs. Correction des nœuds "orphelins" via matching par ID. Ajout de l\'auto-tagging pour les nouveaux appareils OIDC.'
            : 'Major OIDC update! Support for email-style usernames (user@domain.com) to align with ACLs. Fixed "orphaned" nodes via ID-based matching. Added auto-tagging for new OIDC devices.',
        verification: isFr
            ? 'Renommez votre utilisateur en "email" et voyez vos nœuds réapparaître automatiquement.'
            : 'Rename your user to "email" format and watch your nodes reappear automatically.',
      ),
      WhatsNewVersion(
        version: '1.4.97',
        title: isFr ? 'Renommer l\'Utilisateur (OIDC)' : 'Rename User (OIDC)',
        description: isFr
            ? 'Vous pouvez maintenant renommer les utilisateurs ! Idéal pour corriger les identifiants techniques (ID) générés par OIDC (Google) en noms lisibles (ex: "Jean").'
            : 'You can now rename users! Perfect for fixing technical IDs generated by OIDC (Google) into readable names (e.g., "John").',
        verification: isFr
            ? 'Option "Renommer" disponible dans le menu (...) de la liste des utilisateurs.'
            : '"Rename" option available in the User List (...) menu.',
      ),
      WhatsNewVersion(
        version: '1.4.96',
        title: isFr
            ? 'Historique des Versions & Nettoyage'
            : 'Version History & Cleanup',
        description: isFr
            ? 'Ajout de cet écran "Nouveautés" pour suivre les évolutions de l\'application. Nettoyage du code et suppression des fichiers de tests obsolètes pour une meilleure stabilité.'
            : 'Added this "What\'s New" screen to track application changes. Code cleanup and removal of obsolete test files for better stability.',
        verification: isFr
            ? 'Vous consultez actuellement cet écran !'
            : 'You are currently viewing this screen!',
      ),
    ];
  }
}
