class WhatsNewVersion {
  final String version;
  final String title;
  final String description;
  final String verification;

  const WhatsNewVersion({
    required this.version,
    required this.title,
    required this.description,
    required this.verification,
  });

  static List<WhatsNewVersion> getVersions(bool isFr) {
    return [
      WhatsNewVersion(
        version: '1.5.103',
        title: isFr
            ? 'Support des Commentaires ACL (HuJSON)'
            : 'ACL Comments Support (HuJSON)',
        description: isFr
            ? 'Les commentaires (//) dans vos ACL sont désormais correctement gérés par les vues Graphique et Puzzle. Plus de crash lors de la visualisation de configurations complexes !'
            : 'Comments (//) in your ACLs are now correctly handled by Graph and Puzzle views. No more crashes when viewing complex configurations!',
        verification: isFr
            ? 'Ajoutez un commentaire "// test" dans l\'éditeur ACL et ouvrez la vue Puzzle.'
            : 'Add a "// test" comment in the ACL editor and open the Puzzle view.',
      ),
      WhatsNewVersion(
        version: '1.5.102',
        title:
            isFr ? 'Support OIDC Avancé & ACLs' : 'Advanced OIDC & ACL Support',
        description: isFr
            ? 'Mise à jour majeure pour OIDC ! Support des noms d\'utilisateurs type email (user@domaine.com) pour s\'aligner avec les ACLs. Correction des nœuds "orphelins" via matching par ID. Ajout de l\'auto-tagging pour les nouveaux appareils OIDC.'
            : 'Major OIDC update! Support for email-style usernames (user@domain.com) to align with ACLs. Fixed "orphaned" nodes via ID-based matching. Added auto-tagging for new OIDC devices.',
        verification: isFr
            ? 'Renommez votre utilisateur en "email" et voyez vos nœuds réapparaître automatiquement.'
            : 'Rename your user to "email" format and watch your nodes reappear automatically.',
      ),
      WhatsNewVersion(
        version: '1.4.97',
        title: isFr ? 'Renommer l\'Utilisateur (OIDC)' : 'Rename User (OIDC)',
        description: isFr
            ? 'Vous pouvez maintenant renommer les utilisateurs ! Idéal pour corriger les identifiants techniques (ID) générés par OIDC (Google) en noms lisibles (ex: "Jean").'
            : 'You can now rename users! Perfect for fixing technical IDs generated by OIDC (Google) into readable names (e.g., "John").',
        verification: isFr
            ? 'Option "Renommer" disponible dans le menu (...) de la liste des utilisateurs.'
            : '"Rename" option available in the User List (...) menu.',
      ),
      WhatsNewVersion(
        version: '1.4.96',
        title: isFr
            ? 'Historique des Versions & Nettoyage'
            : 'Version History & Cleanup',
        description: isFr
            ? 'Ajout de cet écran "Nouveautés" pour suivre les évolutions de l\'application. Nettoyage du code et suppression des fichiers de tests obsolètes pour une meilleure stabilité.'
            : 'Added this "What\'s New" screen to track application changes. Code cleanup and removal of obsolete test files for better stability.',
        verification: isFr
            ? 'Vous consultez actuellement cet écran !'
            : 'You are currently viewing this screen!',
      ),
      WhatsNewVersion(
        version: '1.4.95',
        title: isFr ? 'Transition vers v0.28' : 'Transition to v0.28',
        description: isFr
            ? 'Support des changements de l\'API Headscale v0.28. La génération de clés utilise désormais le nouveau système basé sur des ID. La fonctionnalité "Déplacer un nœud" a été supprimée car elle n\'est plus supportée par Headscale.'
            : 'Support for the new Headscale v0.28 API changes. Key generation now uses the new ID-based system. The "Move Node" feature has been removed as it is no longer supported by Headscale.',
        verification: isFr
            ? 'Les nouvelles clés API s\'afficheront avec le préfixe confidentiel "hskey-auth-".'
            : 'New API keys will show with the confidential prefix "hskey-auth-".',
      ),
    ];
  }
}
